// Predefined simulation scenarios

export interface SimulationScenario {
  id: string;
  name: string;
  description: string;
  config: {
    intervalMs: number;
    maxActions: number;
    durationMs: number;
  };
}

export const SIMULATION_SCENARIOS: Record<string, SimulationScenario> = {
  enter_periodically: {
    id: "enter_periodically",
    name: "Enter Periodically",
    description: "Human occasionally presses Enter but doesn't type code",
    config: {
      intervalMs: 3000,        // Press Enter every 3 seconds
      maxActions: 50,          // Maximum 50 Enter presses
      durationMs: 300000,      // Run for 5 minutes max
    },
  },

  ollama_code_generation: {
    id: "ollama_code_generation",
    name: "Ollama Code Generation",
    description: "Human types code generated by Ollama API calls using a lightweight instruct coder model",
    config: {
      intervalMs: 3000,        // Generate code every 3 seconds
      maxActions: 50,          // Maximum 50 API calls
      durationMs: 300000,      // Run for 5 minutes max
    },
  },

  state_service_human: {
    id: "state_service_human",
    name: "State Service Human Model",
    description: "Human behavior simulated using the state service's inference_human endpoint with trained human policy model",
    config: {
      intervalMs: 2500,        // Generate actions every 2.5 seconds
      maxActions: 1000,        // Maximum 1000 API calls
      durationMs: 600000,     // Run for 10 minutes max
    },
  },

  // Future scenarios can be added here:
  /*
  typing_slowly: {
    id: "typing_slowly",
    name: "Slow Typing",
    description: "Human types slowly with realistic pauses",
    config: {
      intervalMs: 1000,
      maxActions: 100,
      durationMs: 600000,
    },
  },
  
  random_behavior: {
    id: "random_behavior", 
    name: "Random Human Behavior",
    description: "Mix of typing, cursor movement, and pauses",
    config: {
      intervalMs: 2000,
      maxActions: 200,
      durationMs: 900000,
    },
  },
  */
};

// Get the default scenario (can be overridden by environment variable)
export function getDefaultScenario(): SimulationScenario {
  const scenarioId = process.env.NEXT_PUBLIC_SIMULATION_SCENARIO || "state_service_human";
  return SIMULATION_SCENARIOS[scenarioId] || SIMULATION_SCENARIOS.state_service_human;
}

// Get scenario by ID
export function getScenario(id: string): SimulationScenario | null {
  return SIMULATION_SCENARIOS[id] || null;
}
